### ISSUE TITLE
Support intent classification by patterns

### ISSUE THREAD

**Issue by kvpolyanskiy** [sberdevices/salutejs#127]
For now salutejs only works with training phrases based on specific examples. It would be cool if it could work with training phrases based on patterns https://developer.sberdevices.ru/docs/ru/platform_services/nlu_guidelines/intents_classify

<img width="429" alt="Screenshot 2021-04-29 at 11 35 35" src="https://user-images.githubusercontent.com/16270387/116524886-93c16d80-a8e0-11eb-908e-1a56d7b2d8fb.png">

Example exported intent with patterns:
```
{
    "id" : 155849,
    "path" : "/Navigation/ShowCatalog",
    "enabled" : true,
    "shared" : false,
    "phrases" : [ ],
    "patterns" : [ "открой|покажи|перейди в) [как] (собрать|собирать) [кубик] [рубик|рубика]" ]
}
```

**Comment by Turanchoks** [comment]
Мы проверили и не нашли разницы между тем, как работают тренировочные фразы в patterns или phrases. Поэтому можно просто положить паттерны, как и обычные фразы, в matchers в salutejs, должно работать. Возвращайся, если не взлетит.

**Comment by kvpolyanskiy** [comment]
Паттерн: (открой|покажи|вернись на) (о|об) [интернет] магазине. Проверочная фраза в тестировании: открой о магазине. Совпадение для
” - 0.21
@ - 1

**Comment by Turanchoks** [comment]
Влили изменения, которые поддерживают patterns/phrases для интентов. Поправим доку, релизним и можно будет использовать!
