### ISSUE TITLE
Move server action parameters to req.variables

### ISSUE THREAD

**Issue by awinogradov** [sberdevices/salutejs#129]
![image](https://user-images.githubusercontent.com/982072/116595241-c775b500-a92b-11eb-9548-ddf928329fda.png)

**Comment by awinogradov** [comment]
@sasha-tlt а почему нам `payment_response` приходит не в payload?

**Comment by sasha-tlt** [comment]
Коллеги из нативного сдк или старос формируют такой экшен, аппы не могут на это влиять

**Comment by awinogradov** [comment]
Вот жешь г*вно
