### ISSUE TITLE
Make TextIntent type weaker

### ISSUE THREAD

**Issue by kvpolyanskiy** [sberdevices/salutejs#133]
I try to create intents from json file like this:
```
import model from './intents.json';

const intents = createIntents<typeof model.intents>(model.intents);
```
and get error: _Property 'action' is missing in type '{ matchers: { type: string; rule: string; }[]; }' but required in type 'Required<ServerActionIntent>'.ts(2344)_

cause is https://github.com/sberdevices/salutejs/blob/master/packages/types/src/salute.ts#L106 it's a stronger type than we get when it is inferred it from json (it's just a string)

**Comment by awinogradov** [comment]
Кинь пример того, что в intents.json плиз

**Comment by kvpolyanskiy** [comment]
> Кинь пример того, что в intents.json плиз

```
{
  "intents": {
    "/Form": {
      "matchers": [],
      "variables": {}
    },
    "/Form/Name": {
      "matchers": [
        {
          "type": "pattern",
          "rule": "{@pymorphy.surn @pymorphy.name}"
        }
      ],
      "variables": {
        "name": {
          "required": true,
          "questions": [
            "Введите имя"
          ]
        },
        "surname": {
          "required": true,
          "questions": [
            "Введите фамилию"
          ]
        }
      }
    }
  },
  "entities": {}
}
```

**Comment by awinogradov** [comment]
Обсудили голосом — проблема в выводе типов из `createIntents`. Перестали работать подсказки интентов и выводится `matchers: string` вместо `matchers: 'phrase' | 'pattern'`.
