### ISSUE TITLE
Make SaluteCommand palyload optional

### ISSUE THREAD

**Issue by kvpolyanskiy** [sberdevices/salutejs#135]
Is it possible to make payload in type SaluteCommand optional, because sometimes it's enough to have only type in command. e.g.
```
res.appendCommand({ type: 'confirm' })
```

**Comment by awinogradov** [comment]
Can you make PR with the fix here https://github.com/sberdevices/salutejs/blob/69bac04bb8721267ed84e0823c37eec582283656/packages/types/src/salute.ts#L51 ?

**Comment by kvpolyanskiy** [comment]
https://github.com/sberdevices/salutejs/pull/136
