### ISSUE TITLE
Cannot read property 'current_app' of undefined

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salutejs#150]
Возникает при запуске на сбербокс (из каталога и голосом) для опубликованного смартапа.
```
TypeError: Cannot read property 'current_app' of undefined
at Object.get state [as state] (/workspace/node_modules/@salutejs/scenario/dist/lib/createSaluteRequest.js:28:41)
```

При запуске черновика (голосом) до публикации - ошибки не было. 
В приложении сберсалют iOS (голосом) такой проблемы не наблюдается.

**Comment by christinadomanskaya** [comment]
@snyuryev можно пример message id?
