### ISSUE TITLE
Не хватает типа Surface = SBOL

### ISSUE THREAD

**Issue by vitalets** [sberdevices/salutejs#259]
[ссылка](https://github.com/sberdevices/salutejs/blob/3e2004565afe1f44059744d486b8446534a6f0a0/packages/scenario/src/lib/types/systemMessage.ts#L35)

**Comment by sasha-tlt** [comment]
@vitalets, поправлено в [0.25.0](https://github.com/sberdevices/salutejs/releases/tag/%40salutejs%2Fscenario%400.25.0)

**Comment by vitalets** [comment]
@sasha-tlt Привет! Спасибо!!
А можно это увидеть в [@salutejs/types](https://www.npmjs.com/package/@salutejs/types)?
