### ISSUE TITLE
Лишняя вложенность при отправке команде через appendData

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salutejs#96]
Отравляю команду следующим образом:
```
const helpPayload = { path: '/about' };
const helpCommand = { type: 'smart_app_data', payload: helpPayload };
res.appendCommand(helpCommand);
```

На клиент в onData приходит:
```
{"type":"smart_app_data","smart_app_data":{"type":"smart_app_data","payload":{"path":"/about"}},"sdk_meta":{"mid":1618346995063}}
```

кажется должно быть
```
{"type":"smart_app_data","smart_app_data":{"path":"/about"},"sdk_meta":{"mid":1618346995063}}
```

**Comment by sasha-tlt** [comment]
@snyuryev, в appendCommand нужно передавать payload, этот хелпер сам обернет в smart_app_data. Мы посчитали, что так удобнее, меньше кода писать

**Comment by snyuryev** [comment]
@sasha-tlt да было бы удобнее, но сейчас нет возможности передать payload в appendCommand - там ожидается конкретный тип SaluteCommand:

```
const helpPayload = { path: '/about' };
res.appendCommand(helpPayload);
```

```
Argument of type '{ path: string; }' is not assignable to parameter of type 'SaluteCommand'.
```

**Comment by sasha-tlt** [comment]
@snyuryev, обязательно должен быть type. Вот так может выглядеть твоя команда:
```ts
const helpPayload = { path: '/about' };

res.appendCommand({ type: 'SET_PATH', payload: helpPayload });
```

**Comment by snyuryev** [comment]
@sasha-tlt понял, 
а зачем type обязательный?

**Comment by sasha-tlt** [comment]
@snyuryev, чтобы иметь возможность отличать команды друг от друга. Делали формат, похожий на экшены в редаксе

**Comment by snyuryev** [comment]
@sasha-tlt спасибо, понятно.
